arch: arm64
os: linux
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - wget https://github.com/joan2937/pigpio/archive/master.tar.gz
  - tar xf master.tar.gz
  - cd pigpio-master
  - make
  - sudo make install
  - cd -
  - pip install wheel
install:
  - python setup.py bdist_wheel
  - pip install --no-use-pep517 dist/*.whl -U
script:
  - python tests/test_vestel.py -v